

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, \
	username VARCHAR(25), \
	hash VARCHAR(255), \
	salt VARCHAR(255) \
)

CREATE TABLE sessions (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, \
	username VARCHAR(255), \
	session_id VARCHAR(255), \
	salt VARCHAR(255)
)

CREATE TABLE anchor (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, \
	anchor_name VARCHAR(25),
	anchor_location VARCHAR(25)
)

port 5432